### ISSUE TITLE
References to non-existent files in package.json

### ISSUE THREAD

**Issue by RinkAttendant6** [snowyu/json-canonicalize.ts#22]
The paths referenced in package.json (`./esm5/index.js` and `./esm2015/index.js`) do not appear to point to valid files in the distributed package.

This is causing a problem for tools like Vite that use the `module` field to locate the files.

I think these are the correct paths based on the contents of the package in node_modules:

```json
  "module": "./bundles/index.esm.js",
  "es2015": "./bundles/index.esm.js",
```

**Comment by snowyu** [comment]
Why the index.js file is invalid in the `esm` and `esm2015` folder? More details pls.

**Comment by RinkAttendant6** [comment]
I can't find an esm5 or esm2015 folder in the node_modules folder, on npm, or in the original source code on GitHub. Are these folders supposed to exist?

**Comment by snowyu** [comment]
Enh, I got it. It seems that the	`esm*` of files in `package.json` can not work now.

**Comment by RinkAttendant6** [comment]
Thanks for the prompt response and fix!
